replicaCount: 1

image:
  repository: rabbitmq
  tag: "3.13-management"
  pullPolicy: IfNotPresent

rabbitmq:
  username: devuser        # dev-логин (можешь переопределить параметрами в ArgoCD)
  password: devpassword    # dev-пароль

service:
  type: ClusterIP
  amqpPort: 5672
  managementPort: 15672
  nodePort: 31672

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: rabbitmq-dev.mycum.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - rabbitmq-dev.mycum.ru
      secretName: rabbitmq-dev-tls

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
