apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq-dev.fullname" . }}
  labels:
    app: {{ include "rabbitmq-dev.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "rabbitmq-dev.name" . }}
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.service.amqpPort }}
    - name: http
      port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
