apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq-dev.fullname" . }}
  labels:
    app: {{ include "rabbitmq-dev.name" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "rabbitmq-dev.name" . }}
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.service.amqpPort }}
      nodePort: {{ .Values.service.nodePort }}