apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-config
type: Opaque
stringData:
  rabbitmq.conf: |-
    # твой конфиг
    listeners.tcp.default = 5672
    management.tcp.port   = 15672
    management.tcp.ip     = 0.0.0.0
    loopback_users.guest  = false
    # ... и всё остальное, что хочешь
